import styled from 'styled-components';
const Buttonshark= styled.button`
  font-size:15px;
  font-family:Arial;
  width:140px;
  height:50px;
  border-width:1px;
  color:white;
  border-color:#d6bcd6;
  position:fixed;
  font-weight:bold;
  border-top-left-radius:15px;
  border-top-right-radius:15px;
  border-bottom-left-radius:15px;
  border-bottom-right-radius:15px;
  box-shadow: 3px 4px 0px 0px #899599;
  margin-top:3rem;
  margin-left:55rem;
  text-shadow: 0px 1px 0px #e1e2ed;
  background:linear-gradient(#6C8493, #263642);`;
export default Buttonshark;